# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    deploy:
      name: 'Deploy to Neocities'
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: kognise/neocities-deploy-action@v1
          with:
            neocities_token: ${{ secrets.NEOCITIES_TOKEN }}
            directory: '.'
